SHELL = /bin/sh
#
default :
	echo "Please invoke this makefile using sdssmake"
all:
	;
install :
	$(SDSSTOOLS_DIR)/bin/install_ups_table idlutils.table \
							$(IDLUTILS_DIR)/ups
clean :
	rm -f *~ core *.bak *.orig *.old .#* #*#
