#
# IDL support utilities for spectro2d and the fibermapper
#
SHELL = /bin/sh
#
all :;

#
# Install things in their proper places in $(IDLUTILS_DIR)
#
install :
	-@ cp ebcasc.dat $(IDLUTILS_DIR)/goddard/data

clean :
	- /bin/rm -f *~ core
