#
# IDL support utilities for spectro2d and the fibermapper
#
SHELL = /bin/sh
#
all :

#
# Install things in their proper places in $(IDLUTILS_DIR)
#
install :
	- cp *.so $(IDLUTILS_DIR)/lib

clean :
	- /bin/rm -f *~ core *.so



